version: "3.8"

services:
  djangoshop:
    build: ./djangoshop
    ports:
      - "8000:8000"
    volumes:
      - ./djangoshop:/app

  vuecandyshop:
    build:
      context: ./vuecandyshop
      args:
        - VUE_APP_API_URL=http://localhost:8000
    # environment:
    # - VUE_APP_API_URL=http://flaskcandyshop:8000
    ports:
      - "8080:8080"
    depends_on:
      - djangoshop
